### ISSUE TITLE
[FIX] SmartAI 4.3.4 support!

### ISSUE THREAD

**Issue by cooler-SAI** [Ovahlord/TrinityCore#15]
Hey,guys! nice job here! I love Cataclysm! so, if you need a little help - here we go!
SmartAI scripts for all 4.3.4  addon. enjoy it)

https://github.com/cooler-SAI/patch-Lab/tree/master/patch-Cata%20434

**Comment by Ovahlord** [comment]
Hey there~

I think it would be better if you create pull requests for single parts and update the parts while you're at it.

If you decide to do so update your creature text parts to use broadcast text IDs and also I want to know if these scripts are sniff based because I want validated data in here only.

**Comment by cooler-SAI** [comment]
oki
