### ISSUE TITLE
Spells

### ISSUE THREAD

**Issue by CrossUCI** [Ovahlord/TrinityCore#19]
Paladin Retribution
@Crypticaz already say one of the problem, in the same specialization retribution , the talent Act of Sacrifice do not see that it work, it supose that if you have an impairing effect and you cleanse on yourself it will remove one impairing effect, only show the effect of the cleanse but it dont remove the effect. I prove this in a duel with a Shaman and the Frost Shock, it not remove.
Shaman Enhancement
Maelstrom Weapon it supose that when you arrive to five charges you cast an spell instantly, well it works, but the buff it is only remove when you casting Lightning, but healings or Frogs, not remove the aura, is forever.
Mage Fire
Hot Streak apparently not working, it never show the aura so you can not cast Pyroblast instantly.

**Comment by Ovahlord** [comment]
You are not using my core, are you? I get the feeling you use something else because two of the three issues are invalid.

Tested Maelstrom Weapon: I had 5 stacks, casted healing spells: works. The stacks are removed. I casted Hex on an enemy with 5 stacks: works. Invalid issue.

Hot Streak: works
Keep in mind that the normal Hot Streak has a 25% chance to trigger on critical strikes.
![wowscrnshot_100118_014732](https://user-images.githubusercontent.com/18347559/46264405-c0405d80-c51c-11e8-80f9-0142cc2135a9.jpg)

Acts of Sacrifice however is a valid issue.

**Comment by CrossUCI** [comment]
Yes i am using your core, i mounted like a pvp for a lot of friends enter it, the first issue i review myself as i said but the other two was a report to me from friends but before answer you i tested and for me i do not work , i have a question when you imported de world database 4.3.4.34 when you open the worlserver.exe i assume that is not necessary to import the update from the folder custom , because it do it the own server.

**Comment by Ovahlord** [comment]
You need to apply updates from  sql/updates/world/4.3.4    and   sql/updates/world/custom afterwards.

**Comment by CrossUCI** [comment]
You have all right ,after apply the updates Hot Streak work fine as Maelstrom Weapon, but i see something wrong, correct me if i am wrong, the shaman totem Searing Totem you summon it, and do not attack the target

**Comment by Ovahlord** [comment]
No response or action so I consider this report as abandoned.
