### ISSUE TITLE
Questchain buggy?

### ISSUE THREAD

**Issue by Mysterium** [Ovahlord/TrinityCore#23]
Hi

i think the questchain is buggy.
ex. quest Felendren the Banished (8335), after completing the prequest Aggression (8334) the quest is not available. The DB values seems legit.
Saw the same in duskhaven (worgen, quest "grandma's cat").

**Comment by Ovahlord** [comment]
Usually this happens when the quest_template_addon collide with the sniffed quest chain values from the quest_template so I suspect the quest_template_addon to have a flaw.

In regard to Duskhaven I cannot say anything about it just yet because I did not work on these quests so far. My part has been until the first terrain change at the moment.

**Comment by Mysterium** [comment]
Hello,

thanks for the fast reply. You r right, it was a problem in the quest_template_addon.
Fix:
UPDATE `quest_template_addon` SET `NextQuestID` = 8488 WHERE (ID = 8487);
UPDATE `quest_template` SET `Flags` = 136 WHERE (ID = 8335);
UPDATE `quest_template_addon` SET `PrevQuestID` = 8335 WHERE (ID = 8347);

Maybe the flag? idk, but its fixed now.

Btw, it would be nice if you could fix the whole starting areas.

**Comment by Mysterium** [comment]
Reverted the changes and it works with yours.
